config/routes.rb
Rails.application.routes.draw do

  devise_for :users, :controllers => {:registrations => :registrations}

  resources :items

  resources :users, only: [:show]

  root 'home#index'

end

app/models/item.rb
class Item < ActiveRecord::Base
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable

  has_many :items, dependent: :destroy

  before_save { self.role ||= :standard }
  enum role: [:standard, :premium, :admin]

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  include Pundit
  protect_from_forgery with: :exception
  before_action :authenticate_user!

  def after_sign_in_path_for(resources)
    user_path(current_user)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  skip_before_action :authenticate_user!

  def index
  end
end

app/controllers/item_controller.rb
class ItemController < ApplicationController
  def index
  end

  def show
  end

  def new
  end

  def create
  end

  def edit
  end

  def update
  end

  def destroy
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  def index
    @items = Item.all
  end

  def show
    @item = Item.find(params[:id])
  end

  def new
    @item = Item.new
  end

  def create
    @item = current_user.items.new(item_params)

    if @item.save
      flash[:notice] = "Wiki was saved successfully."
      redirect_to @item
    else
      flash.now[:alert] = "There was an error saving the item. Please try again."
      render :new
    end
  end

  def edit
    @item = Item.find(params[:id])
    authorize @item
  end

  def update
    @item = Item.find(params[:id])
    authorize @item
    if @item.update_attributes(item_params)
     flash[:notice] = "Wiki was updated successfully."
      redirect_to @item
    else
     flash.now[:alert] = "There was an error saving the item. Please try again."
     render :edit
    end
  end

  def destroy
    @item = Item.find(params[:id])
    authorize @item
    if @item.destroy
      flash[:notice] = "\"#{@item.title}\" was deleted successfully."
      redirect_to items_path
    else
      flash.now[:alert] = "There was an error deleting the item."
      render :show
    end
   end

   private
   def item_params
    params.require(:item).permit(:title, :body)
   end

end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
  protected
  def after_update_path_for(resource)
    user_path(resource)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @items = current_user.items
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/registrations_helper.rb
module RegistrationsHelper
end

app/views/home/index.html.erb
<h1>Home#index</h1>
<p>Find me in app/views/home/index.html.erb</p>

app/views/items/_form.html.erb
<%= form_for @item do |f| %>
  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title, class: 'form-control', placeholder: "Enter Wiki title" %>
  </div>
  <div class="form-group">
    <%= f.label :body %>
    <%= f.text_area :body, rows: 8, class: 'form-control', placeholder: "Enter Wiki body" %>
  </div>
  <div class="form-group">
    <%= f.submit "Save", class: 'btn btn-success' %>
  </div>
<% end %>

app/views/items/_item.html.erb
<div class="media">
  <div class="media-body">
    <h4 class="media-heading">
      <%= link_to item.title, item %>
    </h4>
  </div>
</div>

app/views/items/edit.html.erb
<h1>Edit Wiki</h1>

<div class="row">
  <div class="col-md-4">
    <p>Guidelines for items</p>
    <ul>
      <li>Guideline 1</li>
      <li>Guideline 2</li>
      <li>Guideline 3</li>
    </ul>
  </div>
  <div class="col-md-8">
    <%= render partial: 'form', locals: { item: @item } %>
  </div>
</div>

app/views/items/index.html.erb
<h1>All Wiki's</h1>
<%= render @items %>

app/views/items/new.html.erb
<h1>New Wiki</h1>

<div class="row">
  <div class="col-md-4">
    <p>Guidelines for Wiki's</p>
    <ul>
      <li>Guideline 1</li>
      <li>Guideline 2</li>
      <li>Guideline 3</li>
    </ul>
  </div>
  <div class="col-md-8">
      <%= render partial: 'form', locals: { item: @item } %>
  </div>
</div>

app/views/items/show.html.erb
 <h1><%= @item.title %></h1>

 <div class="row">
   <div class="col-md-8">
     <p><%= @item.body %></p>
   </div>
 <div class="col-md-4">
   <%= link_to "Edit", edit_item_path(@item), class: 'btn btn-success' %>
   <%= link_to "Delete Post", @item, method: :delete, class: 'btn btn-danger', data: {confirm: 'Are you sure you want to delete this Wiki?'} %>
   </div>
 </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Wiki</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>


  <div class="container">
    <ul class="nav nav-tabs">
      <div class="pull-left">
        <% if user_signed_in? %>
          <%= link_to "User Wiki's", current_user %> |
          <%= link_to "All Wiki's", items_path %>
        <% end %>
      </div>
    </ul>
  </div>


  <div class="container">
    <ul class="nav nav-tabs">
      <div class="pull-right">
        <% if user_signed_in? %>
          Signed in as: <strong><%= current_user.email %></strong> |
          <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> - <%= link_to "Sign Out", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
        <% else %>
          <%= link_to "Log In", new_user_session_path, :class => 'navbar-link'  %> |
          <%= link_to "Sign Up", new_user_registration_path, :class => 'navbar-link'  %>
        <% end %>
      </div>
    </ul>

  <div class="flash">
    <% if flash[:notice] %>
      <div class="alert alert-success">
        <button type="button" class="close" data_dismiss="alert">&times;</button>
        <%= flash[:notice] %>
      </div>
    <% elsif flash[:alert] %>
      <div class="alert alert-danger">
        <button type="button" class="close" data_dismiss="alert">&times;</button>
        <%= flash[:alert] %>
      </div>
    <% elsif flash[:alert] %>
      <div class="alert alert-warning">
        <button type="button" class="close" data_dismiss="alert">&times;</button>
        <%= flash[:alert] %>
      </div>
    <% end %>
  </div>

<%= yield %>

</body>
</html>

app/views/users/show.html.erb
<h1>Wikis for <%= current_user.email %> </h1>
<%= render @items %>